apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ((k8s-name))
    project: ((app-name))
  name: ((k8s-name))
  namespace: ((k8s-namespace))
spec:
  progressDeadlineSeconds: 600
  replicas: ((k8s-replicas))
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: ((k8s-name))
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ((k8s-name))
    spec:
      containers:
        - env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          image: "registry-vpc.cn-shenzhen.aliyuncs.com/((app-image)):((app-tag))"
          imagePullPolicy: Always
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 7
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: ((app-port))
            timeoutSeconds: 1
          name: app
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /app/config.yaml
              name: ((k8s-name))
              subPath: config.yaml
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: gins-docker-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: ((k8s-name))
          name: ((k8s-name))

# 说明：
# ((k8s-namespace)) 命名空间，一般测服：test，正服：default
# ((k8s-replicas)) 实例数量，一般测服：1，正服：2
# ((k8s-name)) 应用在 k8s 的名称，例如：gins-demo
# ((app-name)) 应用名称，例如：gins.demo
# ((app-port)) 应用监听端口，例如：8080
# ((app-image)) 镜像名称，例如：ginsgroup/go-demo
# ((app-tag)) 镜像版本，一般测服：latest，正服：v1.0.0
